### ISSUE TITLE
benchmarks for vln pallets

### ISSUE THREAD

**Issue by stanly-johnson** [virto-network/virto-node#103]
How about benchmarks for vln custom pallets before going for parachain registration on Kusama?

- [x] payment (#155)
- [ ] communities

**Comment by olanod** [comment]
This is definitely a must do before Kusama for sure. Although first we probably will spend some more time in the testnet world polishing the core functionality.

**Comment by stanly-johnson** [comment]
I think the rates pallet looks good from a permisionless perspective. Adding weights to it should make it good to go for web3 grant. Wdyt @olanod ?
