### ISSUE TITLE
Integrate pallet-assets-freezer

### ISSUE THREAD

**Issue by stanly-johnson** [virto-network/virto-node#113]
Replace [MockAssets](https://github.com/valibre-org/vln-node/blob/52017419b617b6694a45714bbe34b918777744f0/runtime/src/lib.rs#L448) with pallet-assets-freezer

**Comment by stanly-johnson** [comment]
Hey @olanod looks like this is a major blocker for a production ready version of escrow pallet, should I rework the pallet to use tokens pallet like before?

**Comment by olanod** [comment]
I think so, the assets freezer pallet implementation got ... frozen 🥶

**Comment by olanod** [comment]
No work on assets pallet and orml-tokens does the job
