### ISSUE TITLE
Metadata v14

### ISSUE THREAD

**Issue by olanod** [virto-network/virto-node#120]
Metadata v14 is being introduced ecosystem-wide in https://github.com/paritytech/substrate/pull/8615 and with [Sube 1.0](https://github.com/valibre-org/sube/milestone/1) we'll be able to query and submit extrinsics dynamically from our Valor based API.

**Comment by olanod** [comment]
@stanly-johnson do you think the linked branch that is usually updated with Substrate master would break the parachain stuff that we depend on? but maybe worth a try? 😃

**Comment by stanly-johnson** [comment]
Sure will work on this, I think the parachain stuff will work but the xtokens/xcm transfer won't work.

**Comment by olanod** [comment]
The long-awaited PR got merged!
