### ISSUE TITLE
Permisionless version of escrow pallet

### ISSUE THREAD

**Issue by stanly-johnson** [virto-network/virto-node#128]
One of the things that could make escrow pallet more "permissionless" would be to have a council in place of a whitelist judge. In case of a dispute the council can vote on wheter to release/return the escrow. Members of this council have to lock in tokens to be part of the council, which should make them invested in the success of the network. This of course assumes a token based model.

What do you think? @olanod

**Comment by olanod** [comment]
**For disputes**: From the point of view of the escrow pallet, it shouldn't care about councils or whatever, each escrow when created gets assigned a designated origin that will have the permissions to resolve the conflict, this origin can be stored in the `EscrowDetail` and we can get it from a configurable generic provider(e.g. a `DisputeResolver::get_origin()`). For now we just provide an implementation that returns the Sudo origin and later we create a more dynamic version that can get the the canonical account of community which could be ruled by a council or whatever the community decides.

**For the escrow creator**:  In https://github.com/virto-network/virto-node/issues/141 we would tackle how to incentivize the release of the escrow, there wouldn't be anything else to make it more "permissionless" other than the usual fees, if its necessary in the future we can add a more complex fee system that allows charging percentages based on the payment amount or something but it wouldn't be necessary for now.
