### ISSUE TITLE
Community registration

### ISSUE THREAD

**Issue by olanod** [virto-network/virto-node#133]
**Background**

Becoming a community comes with specific requirements that should not be straightforward to fulfill since communities have the big responsibility of maintaining the infrastructure used by their members and have the potential of becoming lucrative since they tax those users to become self-sustainable.

```
                  ^
                 / \
                /   \
               /Union\
              /_______\
             /    |    \      
            /     |     \       
           / Comm.| S.P. \       △  
          /_____ _|_______\      | ++ effort
         /        |        \     | (money/time)
        / Merchant| Client  \
       /__________|__________\
      /                       \
     /     registered user     \
    /___________________________\
   /                             \
  /           new user            \
 /_________________________________\

```
In our initial testnet-only iteration though we can start with simpler requirements. An extrinsic registering a community can initially just require some funds(`KSM`) to be locked, it would also accept a desired `CommunityID` and the domain of its Matrix homeserver, that(in a separate ticket) would be verified from an off-chain worker. 

**Note about `CommunityID`s**, it isn't an arbitraty number, it is a `u32` number that contains information about where the community is located in the world, from this number we can construct an [H3Index](https://h3geo.org/docs/core-library/h3Indexing) that represents a hexagonal cell that roughly covers a 5km2 patch of land(validation of IDs also a separate issue).  
When storing said number on-chain to be the index of our community data, it should be deconstructed as an [`NMap`](https://github.com/paritytech/substrate/blob/master/frame/support/src/storage/types/nmap.rs#L54) of `<u8>/<u8>/<u16>` this translates to a cheap mechanism for clients to know what communities are located in a certain area without requiring off-chain indexing of data and running expensive geo-lookups.

**Summary**
The initial implementation should follow along the lines of:
- Creating a "communities pallet" if not existent
- Define the `CommunityId` type as wrapper for a `u32`
- Create an extrinsic call `register` that accepts a `CommunityID` and `home_server_url`.
- Freeze a configurable deposit in KSM
- Store community data and emit event

**Comment by stanly-johnson** [comment]
`Freeze a configurable deposit in KSM`
Does this have to be strictly KSM or the base token of balances pallet? Also I assume this means to just reserve the amount in the community creators account, is there a scenario where this deposit is claimable, like a destroy extrinsic? Extending that should we ensure only the creator can destroy the community?

**Comment by olanod** [comment]
Base token of balances pallet which on mainnet is KSM 😉

Regarding the reserve of assets perhaps we can ship the initial version with already a slightly more interesting set-up. Since communities are groups of people, somehow the concept of a "creator" doesn't seem right to me, we should from the start require a threshold of how many accounts are needed to create the community that we define as a configurable parameter in the pallet and only until enough accounts have expressed their intent to stablish a community in the cell then the community is actually created(e.g. cell goes from a waiting state to founded or similar). 

Also I'm thinking this initial "creation" can be automatic and be done together with https://github.com/virto-network/virto-node/issues/134 meaning we update the cell status when users register/upgrade-account, since with that issue we will be storing already information about the cell and its population we just change the state of the cell after a number of users have done their registration.

An example of the info about a cell, not sure what you think
```rust
type Population = u16;
enum Cell {
    Free(Population), // every time someone registers in the cell we increase the population
    Waiting(Population, u16), // The threshold was reached and we track the supporters of the community creation?
    Annexed(Population, CellId), // cells can be "conquered" by neighbor communities
    Community {
        name: String, // or equivalent type with size limit
        poulation: Population,
        cells: Vec<CellId>, // perhaps there's a configurable limit of how big communities can be
    }
}
```
And as mentioned in the issue we store it under an `NMap` of `<u8>/<u8>/<u16>`
