### ISSUE TITLE
Payment(escrow) DisputeResolver

### ISSUE THREAD

**Issue by olanod** [virto-network/virto-node#143]
Payment/Escrow details should also store a `resolver_account` which is set at the time of creation of the payment that we get from a `DisputeResolver::get_origin`. When resolving, we just check if the `resolver_account` matches the calling origin.

With the initial implementation let's create a `DisputeResolver` that just returns the Sudo origin.

**Comment by stanly-johnson** [comment]
How would this be different from the [JudgeWhitelist](https://github.com/virto-network/virto-node/blob/7b6def7aabbd0e380caa5dddc780b0a7b36d0dd4/pallets/payment/src/lib.rs#L144) we currently have? Is the idea to have both seller/buyer decide on the Resolver for every payment?

**Comment by olanod** [comment]
The judge whitelist is a global and quite static list of accounts that can resolve disputes for **every payment**. This is about making it more granular and generic allowing users of the pallet implement different ways of getting the account that is allowed to resolve the dispute which could be different for every payment. 
Later we would just implement a different kind of `DisputeResolver` that can get a judge from whatever like an oracle, deterministically generated accounts or special rules related to the communities like the location of the seller.
