### ISSUE TITLE
Payments are sent immediately to the destination

### ISSUE THREAD

**Issue by olanod** [virto-network/virto-node#147]
Currently payments are reserved in the origin account and only transferred to the destination after the release call is made. We should change it so the transfer of funds is made immediately when the payment is created but the funds are reserved on arrival.

This can help the seller prove to another party that it has funds that are just pending a release. i.e. a seller could borrow liquidity from other protocol using its future funds as guarantee.

**Comment by stanly-johnson** [comment]
Not sure I understand the flow here, the cancel/release permissions and incentives are not aligned here.
- Release : Since the amount is reserved in the account of the seller, the permission to release is also with the seller
- Cancel : The cancellation should also be initiated by the seller

**Comment by olanod** [comment]
I'm not sure I quite understand the confusion but things should remain mostly untouched, there will be a change though in the way the release incentive works. Currently both the payment `amount` and the `release_incentive` are reserved from the origin account creating the payment, with this change we only reserve the `incentive_amount` from the origin and the `amount` is transferred and reserved in the destination account. The payment release is still done by the creator of the payment that has the incentive to do so since there are some her funds in reserve and in the same call we also un-reserve the `payment.amount` from the destination account.

**Comment by stanly-johnson** [comment]
Gotcha! I forgot about the `incentive_amount` part :)
