### ISSUE TITLE
apply_fees extrinsic

### ISSUE THREAD

**Issue by stanly-johnson** [virto-network/virto-node#158]
`apply_fees` that returns the amount that is actually sent to the merchant, by default it does nothing and returns the full amount but in our runtime we can configure a different handler that checks what market places the merchant is registered to and applies the discount of that marketplace(e.g. swap cash might take a 1% of commission as it allows people listing their fiat trades in its infrastructure(matrix room))

**Comment by stanly-johnson** [comment]
@olanod Lets say we charge a fee of 1%. What should be done with that amount? Do we just send it to a custom account?

**Comment by olanod** [comment]
No, the handler should tell us what to do with that, I think the function could return a map of account => percentage. The pallet could also enforce some limits in the amount of accounts(or iterate up to a maximum) and even a maximum amount of fees(at least that the sum is not >100%)
