### ISSUE TITLE
Early return in release

### ISSUE THREAD

**Issue by olanod** [virto-network/virto-node#201]
Checking the `release` [code](https://github.com/virto-network/virto-node/blob/master/pallets/payment/src/lib.rs#L199), should we handle the `None` returning early to avoid calling `settle_payment` that reads the storage again?

**Comment by stanly-johnson** [comment]
It doesn't increase the [read count](https://github.com/virto-network/virto-node/blob/5844e33d6c9da56abf52a9e884d7406185f61320/pallets/payment/src/weights.rs#L69) since its same extrinsic, but removed it in #198 since it makes the code more concise.
