### ISSUE TITLE
Kreivo Crowdloan checklist

### ISSUE THREAD

**Issue by olanod** [virto-network/virto-node#231]
The [proposal of Kreivo](https://kusama.polkassembly.io/post/1520) for a common good chain didn't get much attention, but this doesn't mean we'll desist from joining Kusama. This leaves us with the Crowdloan path and everything needed to execute it successfully. This includes

- [ ] ...

**Comment by cuardaigh** [comment]
- [ ] #232
- [ ] #229 
- [ ] #230 
- [ ] #233 
- [ ] #234
- [ ] #223 
- [ ] #196 
- [ ] #192 
- [ ] #224
