### ISSUE TITLE
XCM specific configuration.

### ISSUE THREAD

**Issue by darkforest0202** [virto-network/virto-node#242]
The following XCM configuration is needed for Kreivo and Virto parachains:

- For the native token (DOT/KSM) the relay chain should be recognized as a reserve (not asset hubs).
- For other fungible assets, Asset Hubs parachains should be the reserve.

**Comment by olanod** [comment]
Adding to point 2, should we add the [remote account conversion](https://github.com/paritytech/polkadot/pull/6662) that was added recently so users in our parachain can act on the assets hub with their own accounts instead of every asset being locked in the parachain's sovereign account?

**Comment by darkforest0202** [comment]
Depends on #254

**Comment by darkforest0202** [comment]
Facing an error at the moment when reserve transferring an asset from statemine to kreivo:

 `ERROR: UntrustedReserveLocation`

Investigation is on going.
