### ISSUE TITLE
Kreivo deployment for Kusama

### ISSUE THREAD

**Issue by darkforest0202** [virto-network/virto-node#286]
This issue documents all the necessary steps to conduct the deployment and testing on Kusama.

## Preparation

- [x] Reserve PARA ID - 2,281
- [ ] Set `CreateOrigin` to Root for pallet-assets.
- [x] Health check of chain-spec.
  - [x] Update sudo account.
  - [x] Update PARA ID 2,281 on chain-spec
- [x] Health check with Zombienet
  - [x]  Check if 2000 KSM are enough.
  - [x] Conduct a runtime upgrade locally.
- [x] Get slot on Kusama (#243)

## Deployment

- [ ] Deploy two collators for Kusama and wait until the relay chain node gets fully sync.
- [ ] Wait until parachain is onboarded.

## To perform for unlocking

- [ ] Run benchmarks for all pallets.
- [ ] Complete pallet payments.
- [ ] Runtime upgrade.
- [ ] Disable transaction filters.
- [ ] Create USDT asset (id 1984)
- [ ] Open channel with Asset hub
- [ ] Reserve transfer KSM from relay chain to the parachain.
- [ ] Burn the fake initial supply (in the parachain they will appear as KSM)
- [ ] Reserve transfer USDT from Asset Hub to Kreivo.

**Comment by olanod** [comment]
As we have the parachain live on Kusama I'm closing this, we can have the checklist of "before unlocking" in a new issue :)
