### ISSUE TITLE
Community registration and "removal".

### ISSUE THREAD

**Issue by pandres95** [virto-network/virto-node#292]
## Types

```rs
pub type AccountIdOf<T> = <T as SystemConfig>::AccountId;
pub type CommunityIdOf<T> = <T as Config>::CommunityId;
pub type MemberRankOf<T> = <T as Config>::MemberRank;
pub type AssetIdOf<T> = <<T as Config>::Assets as Inspect<AccountIdOf<T>>>::AssetId;
pub type MemberListOf<T> = Vec<AccountIdOf<T>>;

pub type Cell = u32;

pub type Field<const S: u32> = BoundedVec<u8, ConstU32<S>>;
```

## Structures

```rs
#[derive(TypeInfo, Encode, Decode, MaxEncodedLen)]
#[scale_info(skip_type_params(T))]
pub struct Community<T: crate::Config> {
	pub admin: AccountIdOf<T>,
	pub state: CommunityState,
	pub sufficient_asset_id: Option<AssetIdOf<T>>,
}

#[derive(TypeInfo, Encode, Decode, MaxEncodedLen)]
pub enum CommunityState {
	Awaiting,
	Active,
	Frozen,
	Blocked,
}

#[derive(TypeInfo, Eq, PartialEq, Debug, Clone, Encode, Decode, MaxEncodedLen)]
#[scale_info(skip_type_params(T))]
pub struct CommunityMetadata<T: Config> {
	pub(super) name: Field<64>,
	pub(super) description: Field<256>,
	pub(super) urls: BoundedVec<Field<2000>, T::MaxUrls>,
	pub(super) locations: BoundedVec<Cell, T::MaxLocations>,
}

impl Default for CommunityState {
	fn default() -> Self {
		CommunityState::Awaiting
	}
}

impl<T: Config> Default for CommunityMetadata<T> {
	fn default() -> Self {
		Self {
			name: Default::default(),
			description: Default::default(),
			urls: Default::default(),
			locations: Default::default(),
		}
	}
}
```

## Implementation

- Community application
  - [x] `apply`: Registers an application as new community. Takes an [existential deposit](https://docs.substrate.io/reference/glossary/#existential-deposit) used to create the treasury account.
  - [x] `set_metadata`: Sets some [`CommunityMetadata`] to describe the community.

- Community "removal" (won't do, since `MutateFreeze` hasn't been implemented by [`pallet_assets`](https://paritytech.github.io/substrate/master/pallet_assets/index.html)
  - `freeze`: Allows suspending the operations of the community. This also freezes the assets issued by the community and the ability to create and run polls.
  - `thaw`: Allows reinitiating the operations of the community.

## Pull Requests

- #293

**Comment by olanod** [comment]
I think I'd make the `members` a `member_count` and keep track in a separate storage item the mapping of users and the communities they belong to. It can get quite expensive to decode the `Community` struct when there are a lot of members. If we see ourselves querying the `Community` often to know things like the admin then I would also take the metadata out into a separate storage mapping.  
Locations I think we can optimize them a bit, `H3Index` is a `u64` but for the resolution we need, we could have a `Cell` type that is a `u32`, it's not a high priority to onboard local communities so we can deffer location related topics for a bit later after more thinking :)

**Comment by pandres95** [comment]
@olanod noted.

Actually, after a bit of thinking (and some research), it's feasible to just store community members' list as a [`StorageDoubleMap`](https://paritytech.github.io/substrate/master/frame_support/storage/trait.StorageDoubleMap.html) while storing the `member_count` separately.

Also, changed a bit the structure to keep the metadata as a separate storage. Also, set the location type to match `Cell`.
