### ISSUE TITLE
[Communities] Custom origin

### ISSUE THREAD

**Issue by olanod** [virto-network/virto-node#311]
To allow the maximum flexibility for our communities and their members to execute different permissioned actions in other parts of the system(e.g. in the assets pallet) or even across other chains, we should expose a custom origin(`#[pallet::origin]`) that maps well to the [`BodyPart`](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/xcm/src/v3/junction.rs#L189-L218) of the XCM plurality junction.

BodyPart looks something like this,
```rust
pub enum BodyPart {
	Voice,
	Members { count: u32 },
	Fraction { nom: u32, denom: u32 },
	AtLeastProportion { nom: u32, denom: u32 },
	MoreThanProportion { nom: u32, denom: u32 },
}
```
Our origin type can be a 1:1 mapping or a subset of this

**Comment by pandres95** [comment]
This strategy will be useful for implementing #303. What do you think, @olanod?
